### ISSUE TITLE
2 compilation errors 

### ISSUE THREAD

**Issue by Javinuo** [NVIDIA-Merlin/distributed-embeddings#3]
Hi:
I've met 2 compilation errors while following installation guide. 

I'm using A30 with ngc 22.03 NGC container. (I also tried 22.09 ver but got the same result).

`root@34c11c7a915a:/workspace/distributed-embeddings# make pip_pkg && pip install artifacts/*.whl
/usr/local/cuda/bin/nvcc -c -o embedding_lookup_kernels.cu.o distributed_embeddings/cc/kernels/embedding_lookup_kernels.cu -Ithird_party/cub -I/usr/local/lib/python3.8/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -DEIGEN_MAX_ALIGN_BYTES=64 -O3 -std=c++14 -I. -DGOOGLE_CUDA=1 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -x cu -Xcompiler -fPIC --expt-relaxed-constexpr
/usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/core/platform/file_system.h(579): warning #611-D: overloaded virtual function "tensorflow::FileSystem::FilesExist" is only partially overridden in class "tensorflow::WrappedFileSystem"

/usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/core/platform/file_system.h(579): warning #611-D: overloaded virtual function "tensorflow::FileSystem::CreateDir" is only partially overridden in class "tensorflow::WrappedFileSystem"

/usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/core/platform/env.h(498): warning #611-D: overloaded virtual function "tensorflow::Env::RegisterFileSystem" is only partially overridden in class "tensorflow::EnvWrapper"

distributed_embeddings/cc/kernels/embedding_lookup_kernels.cu(502): error: class "cub::DeviceSelect" has no member "UniqueByKey"

distributed_embeddings/cc/kernels/embedding_lookup_kernels.cu(513): error: class "cub::DeviceSelect" has no member "UniqueByKey"

2 errors detected in the compilation of "distributed_embeddings/cc/kernels/embedding_lookup_kernels.cu".
make: *** [Makefile:43: embedding_lookup_kernels.cu.o] Error 1
`
Could you please take a look?

Thank you

**Comment by skyw** [comment]
Hi,
could you pull all the submodule `git submodule update --init --recursive`
Main now depends on a newer version of CUB. We should update build instructions, @FDecaYed

**Comment by Javinuo** [comment]
Thank you! It's working after CUB is updated.

**Comment by FDecaYed** [comment]
updated build instruction in https://github.com/NVIDIA-Merlin/distributed-embeddings/commit/02e1ed048b01a770473d25963925d2f1714f95d2
