### ISSUE TITLE
NotImplementedError with fewer tables than GPUs

### ISSUE THREAD

**Issue by edknv** [NVIDIA-Merlin/distributed-embeddings#5]
Does the library not support cases where the number of embedding tables is smaller than the number of GPUs, e.g., when we have one embedding table with billions of items but want to shard it across multiple GPUs maybe by using `column_slice_threshold`? It seems that it raises an error in such cases:
https://github.com/NVIDIA-Merlin/distributed-embeddings/blob/c635ed843cf3edbc41f5e9bfc02a5ca2f71b0882/distributed_embeddings/python/layers/dist_model_parallel.py#L272-L273

**Comment by skyw** [comment]
It will be supported in next release which should be coming soon.
The way it is supported will be exactly as you suggested, use `column_slice_threshold` to slice tables. It was not well tested in current release version, so marked as not implemented to prevent surprises.

**Comment by FDecaYed** [comment]
Hi @edknv,
The feature to automatically slice table when there is more worker than table is added in this commit
https://github.com/NVIDIA-Merlin/distributed-embeddings/commit/a5816132ac65d07e1129861dc4404e075cef826e
By default, we do as little slicing as possible, meaning if you run say 7 tables on 8 GPU, just the largest will be sliced 2-way and you get 8 total slices for each worker.
Note that explicitly set column_slice_threshold will disable auto slicing and instead use the user defined threshold. 

Closing now. Please re-open if you find further issue wiht the feature.
